/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.cpp                                           */
/*  DATE        :Wed, Apr 22, 2009                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :SH7619                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
                  


#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif


void HardwareSetup(void)
{
/*
  CPG.MCLKCR.BYTE = 0;
  CPG.MCLKCR.BIT.FLSCS  = 3;
  CPG.MCLKCR.BIT.FLDIVS = 7;
  CPG.FRQCR.WORD = 0;
  CPG.FRQCR.BIT.CKOEN = 1;
  CPG.FRQCR.BIT.STC   = 7;
  CPG.FRQCR.BIT.IFC   = 7;
  CPG.FRQCR.BIT._PFC  = 7;

  HUDI.SDIR.WORD = 0;
  HUDI.SDIR.BIT.TI = 255;
  HUDI.SDID = 0;

  WDT.READ.WTCNT = 0;
  WDT.READ.WTCSR.BYTE = 0;
  WDT.READ.WTCSR.BIT.OVF  = 1;
  WDT.READ.WTCSR.BIT.WTIT = 1;
  WDT.READ.WTCSR.BIT.WOVF = 1;
  WDT.READ.WTCSR.BIT.IOVF = 1;
  WDT.READ.WTCSR.BIT.CKS  = 7;
  WDT.WRITE.WTCNT = 0;
  WDT.WRITE.WTCSR = 0;
*/
}
