/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.cpp                                           */
/*  DATE        :Wed, Mar 11, 2009                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :SH7020                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
                  


#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif


void HardwareSetup(void)
{
/*
  SCI0.SMR.BYTE = 0;
  SCI0.SMR.BIT.CA   = 1;
  SCI0.SMR.BIT.CHR  = 1;
  SCI0.SMR.BIT.PE   = 1;
  SCI0.SMR.BIT.OE   = 1;
  SCI0.SMR.BIT.STOP = 1;
  SCI0.SMR.BIT.MP   = 1;
  SCI0.SMR.BIT.CKS  = 3;
  SCI0.BRR = 0;
  SCI0.SCR.BYTE = 0;
  SCI0.SCR.BIT.TIE  = 1;
  SCI0.SCR.BIT.RIE  = 1;
  SCI0.SCR.BIT.TE   = 1;
  SCI0.SCR.BIT.RE   = 1;
  SCI0.SCR.BIT.MPIE = 1;
  SCI0.SCR.BIT.TEIE = 1;
  SCI0.SCR.BIT.CKE  = 3;
  SCI0.TDR = 0;
  SCI0.SSR.BYTE = 0;
  SCI0.SSR.BIT.TDRE = 1;
  SCI0.SSR.BIT.RDRF = 1;
  SCI0.SSR.BIT.ORER = 1;
  SCI0.SSR.BIT.FER  = 1;
  SCI0.SSR.BIT.PER  = 1;
  SCI0.SSR.BIT.TEND = 1;
  SCI0.SSR.BIT.MPB  = 1;
  SCI0.SSR.BIT.MPBT = 1;
  SCI0.RDR = 0;

*/
}
