/***********************************************************************/
/*                                                                     */
/*  FILE        :vecttbl.c                                             */
/*  DATE        :Wed, Mar 11, 2009                                     */
/*  DESCRIPTION :Initialize of Vector Table                            */
/*  CPU TYPE    :SH7020                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
                  


#include "vect.h"


#pragma section VECTTBL

void *RESET_Vectors[] = {
//;<<VECTOR DATA START (POWER ON RESET)>>
//;0 Power On Reset PC
    (void*)	PowerON_Reset_PC,                                                                                                                
//;<<VECTOR DATA END (POWER ON RESET)>>
// 1 Power On Reset SP
    __secend("S"),
//;<<VECTOR DATA START (MANUAL RESET)>>
//;2 Manual Reset PC
    (void*)	Manual_Reset_PC,                                                                                                                 
//;<<VECTOR DATA END (MANUAL RESET)>>
// 3 Manual Reset SP
    __secend("S")

};
#pragma section INTTBL
void *INT_Vectors[] = {
// 4 Illegal code
    (void*) INT_Illegal_code,
// 5 Reserved
    (void*) Dummy,
// 6 Illegal slot
    (void*) INT_Illegal_slot,
// 7 Reserved
    (void*) Dummy,
// 8 Reserved
    (void*) Dummy,
// 9 CPU Address error
    (void*) INT_CPU_Address,
// 10 DMA Address error
    (void*) INT_DMA_Address,
// 11 NMI
    (void*) INT_NMI,
// 12 User breakpoint trap
    (void*) INT_User_Break,
// 13 Reserved
    (void*) Dummy,
// 14 Reserved
    (void*) Dummy,
// 15 Reserved
    (void*) Dummy,
// 16 Reserved
    (void*) Dummy,
// 17 Reserved
    (void*) Dummy,
// 18 Reserved
    (void*) Dummy,
// 19 Reserved
    (void*) Dummy,
// 20 Reserved
    (void*) Dummy,
// 21 Reserved
    (void*) Dummy,
// 22 Reserved
    (void*) Dummy,
// 23 Reserved
    (void*) Dummy,
// 24 Reserved
    (void*) Dummy,
// 25 Reserved
    (void*) Dummy,
// 26 Reserved
    (void*) Dummy,
// 27 Reserved
    (void*) Dummy,
// 28 Reserved
    (void*) Dummy,
// 29 Reserved
    (void*) Dummy,
// 30 Reserved
    (void*) Dummy,
// 31 Reserved
    (void*) Dummy,
// 32 TRAPA (User Vecter)
    (void*) INT_TRAPA32,
// 33 TRAPA (User Vecter)
    (void*) INT_TRAPA33,
// 34 TRAPA (User Vecter)
    (void*) INT_TRAPA34,
// 35 TRAPA (User Vecter)
    (void*) INT_TRAPA35,
// 36 TRAPA (User Vecter)
    (void*) INT_TRAPA36,
// 37 TRAPA (User Vecter)
    (void*) INT_TRAPA37,
// 38 TRAPA (User Vecter)
    (void*) INT_TRAPA38,
// 39 TRAPA (User Vecter)
    (void*) INT_TRAPA39,
// 40 TRAPA (User Vecter)
    (void*) INT_TRAPA40,
// 41 TRAPA (User Vecter)
    (void*) INT_TRAPA41,
// 42 TRAPA (User Vecter)
    (void*) INT_TRAPA42,
// 43 TRAPA (User Vecter)
    (void*) INT_TRAPA43,
// 44 TRAPA (User Vecter)
    (void*) INT_TRAPA44,
// 45 TRAPA (User Vecter)
    (void*) INT_TRAPA45,
// 46 TRAPA (User Vecter)
    (void*) INT_TRAPA46,
// 47 TRAPA (User Vecter)
    (void*) INT_TRAPA47,
// 48 TRAPA (User Vecter)
    (void*) INT_TRAPA48,
// 49 TRAPA (User Vecter)
    (void*) INT_TRAPA49,
// 50 TRAPA (User Vecter)
    (void*) INT_TRAPA50,
// 51 TRAPA (User Vecter)
    (void*) INT_TRAPA51,
// 52 TRAPA (User Vecter)
    (void*) INT_TRAPA52,
// 53 TRAPA (User Vecter)
    (void*) INT_TRAPA53,
// 54 TRAPA (User Vecter)
    (void*) INT_TRAPA54,
// 55 TRAPA (User Vecter)
    (void*) INT_TRAPA55,
// 56 TRAPA (User Vecter)
    (void*) INT_TRAPA56,
// 57 TRAPA (User Vecter)
    (void*) INT_TRAPA57,
// 58 TRAPA (User Vecter)
    (void*) INT_TRAPA58,
// 59 TRAPA (User Vecter)
    (void*) INT_TRAPA59,
// 60 TRAPA (User Vecter)
    (void*) INT_TRAPA60,
// 61 TRAPA (User Vecter)
    (void*) INT_TRAPA61,
// 62 TRAPA (User Vecter)
    (void*) INT_TRAPA62,
// 63 TRAPA (User Vecter)
    (void*) INT_TRAPA63,
// 64 Interrupt IRQ0
    (void*) INT_IRQ0,
// 65 Interrupt IRQ1
    (void*) INT_IRQ1,
// 66 Interrupt IRQ2
    (void*) INT_IRQ2,
// 67 Interrupt IRQ3
    (void*) INT_IRQ3,
// 68 Interrupt IRQ4
    (void*) INT_IRQ4,
// 69 Interrupt IRQ5
    (void*) INT_IRQ5,
// 70 Interrupt IRQ6
    (void*) INT_IRQ6,
// 71 Interrupt IRQ7
    (void*) INT_IRQ7,
// 72 DMAC0 DEI0
    (void*) INT_DMAC0_DEI0,
// 73 DMAC0 Reserved
    (void*) INT_DMAC0_Reserved,
// 74 DMAC1 DEI1
    (void*) INT_DMAC1_DEI1,
// 75 DMAC1 Reserved
    (void*) INT_DMAC1_Reserved,
// 76 DMAC2 DEI2
    (void*) INT_DMAC2_DEI2,
// 77 DMAC2 Reserved
    (void*) INT_DMAC2_Reserved,
// 78 DMAC3 DEI3
    (void*) INT_DMAC3_DEI3,
// 79 DMAC3 Reserved
    (void*) INT_DMAC3_Reserved,
// 80 ITU0 IMIA0
    (void*) INT_ITU0_IMIA0,
// 81 ITU0 IMIB0
    (void*) INT_ITU0_IMIB0,
// 82 ITU0 OVI0
    (void*) INT_ITU0_OVI0,
// 83 ITU0 Reserved
    (void*) INT_ITU0_Reserved,
// 84 ITU1 IMIA1
    (void*) INT_ITU1_IMIA1,
// 85 ITU1 IMIB1
    (void*) INT_ITU1_IMIB1,
// 86 ITU1 OVI1
    (void*) INT_ITU1_OVI1,
// 87 ITU1 Reserved
    (void*) INT_ITU1_Reserved,
// 88 ITU2 IMIA2
    (void*) INT_ITU2_IMIA2,
// 89 ITU2 IMIB2
    (void*) INT_ITU2_IMIB2,
// 90 ITU2 OVI2
    (void*) INT_ITU2_OVI2,
// 91 ITU2 Reserved
    (void*) INT_ITU2_Reserved,
// 92 ITU3 IMIA3
    (void*) INT_ITU3_IMIA3,
// 93 ITU3 IMIB3
    (void*) INT_ITU3_IMIB3,
// 94 ITU3 OVI3
    (void*) INT_ITU3_OVI3,
// 95 ITU3 Reserved
    (void*) INT_ITU3_Reserved,
// 96 ITU4 IMIA4
    (void*) INT_ITU4_IMIA4,
// 97 ITU4 IMIB4
    (void*) INT_ITU4_IMIB4,
// 98 ITU4 OVI4
    (void*) INT_ITU4_OVI4,
// 99 ITU4 Reserved
    (void*) INT_ITU4_Reserved,
// 100 SCI0 ERI0
    (void*) INT_SCI0_ERI0,
// 101 SCI0 RXI0
    (void*) INT_SCI0_RXI0,
// 102 SCI0 TXI0
    (void*) INT_SCI0_TXI0,
// 103 SCI0 TEI0
    (void*) INT_SCI0_TEI0,
// 104 SCI1 ERI1
    (void*) INT_SCI1_ERI1,
// 105 SCI1 RXI1
    (void*) INT_SCI1_RXI1,
// 106 SCI1 TXI1
    (void*) INT_SCI1_TXI1,
// 107 SCI1 TEI1
    (void*) INT_SCI1_TEI1,
// 108 PRT PEI
    (void*) INT_PRT_PEI,
// 109 PRT Reserved
    (void*) Dummy,
// 110 PRT Reserved
    (void*) Dummy,
// 111 PRT Reserved
    (void*) Dummy,
// 112 WDT ITI
    (void*) INT_WDT_ITI,
// 113 REF CMI
    (void*) INT_REF_CMI,
// 114 REF Reserved
    (void*) Dummy,
// 115 REF Reserved
    (void*) Dummy,
// 116 Reserved
    (void*) Dummy,
// 117 Reserved
    (void*) Dummy,
// 118 Reserved
    (void*) Dummy,
// 119 Reserved
    (void*) Dummy,
// 120 Reserved
    (void*) Dummy,
// 121 Reserved
    (void*) Dummy,
// 122 Reserved
    (void*) Dummy,
// 123 Reserved
    (void*) Dummy,
// 124 Reserved
    (void*) Dummy,
// 125 Reserved
    (void*) Dummy,
// 126 Reserved
    (void*) Dummy,
// 127 Reserved
    (void*) Dummy,
// 128 Reserved
    (void*) Dummy,
// 129 Reserved
    (void*) Dummy,
// 130 Reserved
    (void*) Dummy,
// 131 Reserved
    (void*) Dummy,
// 132 Reserved
    (void*) Dummy,
// 133 Reserved
    (void*) Dummy,
// 134 Reserved
    (void*) Dummy,
// 135 Reserved
    (void*) Dummy,
// 136 Reserved
    (void*) Dummy,
// 137 Reserved
    (void*) Dummy,
// 138 Reserved
    (void*) Dummy,
// 139 Reserved
    (void*) Dummy,
// 140 Reserved
    (void*) Dummy,
// 141 Reserved
    (void*) Dummy,
// 142 Reserved
    (void*) Dummy,
// 143 Reserved
    (void*) Dummy,
// 144 Reserved
    (void*) Dummy,
// 145 Reserved
    (void*) Dummy,
// 146 Reserved
    (void*) Dummy,
// 147 Reserved
    (void*) Dummy,
// 148 Reserved
    (void*) Dummy,
// 149 Reserved
    (void*) Dummy,
// 150 Reserved
    (void*) Dummy,
// 151 Reserved
    (void*) Dummy,
// 152 Reserved
    (void*) Dummy,
// 153 Reserved
    (void*) Dummy,
// 154 Reserved
    (void*) Dummy,
// 155 Reserved
    (void*) Dummy,
// 156 Reserved
    (void*) Dummy,
// 157 Reserved
    (void*) Dummy,
// 158 Reserved
    (void*) Dummy,
// 159 Reserved
    (void*) Dummy,
// 160 Reserved
    (void*) Dummy,
// 161 Reserved
    (void*) Dummy,
// 162 Reserved
    (void*) Dummy,
// 163 Reserved
    (void*) Dummy,
// 164 Reserved
    (void*) Dummy,
// 165 Reserved
    (void*) Dummy,
// 166 Reserved
    (void*) Dummy,
// 127 Reserved
    (void*) Dummy,
// 168 Reserved
    (void*) Dummy,
// 169 Reserved
    (void*) Dummy,
// 170 Reserved
    (void*) Dummy,
// 171 Reserved
    (void*) Dummy,
// 172 Reserved
    (void*) Dummy,
// 173 Reserved
    (void*) Dummy,
// 174 Reserved
    (void*) Dummy,
// 175 Reserved
    (void*) Dummy,
// 176 Reserved
    (void*) Dummy,
// 177 Reserved
    (void*) Dummy,
// 178 Reserved
    (void*) Dummy,
// 179 Reserved
    (void*) Dummy,
// 180 Reserved
    (void*) Dummy,
// 181 Reserved
    (void*) Dummy,
// 182 Reserved
    (void*) Dummy,
// 183 Reserved
    (void*) Dummy,
// 184 Reserved
    (void*) Dummy,
// 185 Reserved
    (void*) Dummy,
// 186 Reserved
    (void*) Dummy,
// 187 Reserved
    (void*) Dummy,
// 188 Reserved
    (void*) Dummy,
// 189 Reserved
    (void*) Dummy,
// 190 Reserved
    (void*) Dummy,
// 191 Reserved
    (void*) Dummy,
// 192 Reserved
    (void*) Dummy,
// 193 Reserved
    (void*) Dummy,
// 194 Reserved
    (void*) Dummy,
// 195 Reserved
    (void*) Dummy,
// 196 Reserved
    (void*) Dummy,
// 197 Reserved
    (void*) Dummy,
// 198 Reserved
    (void*) Dummy,
// 199 Reserved
    (void*) Dummy,
// 200 Reserved
    (void*) Dummy,
// 201 Reserved
    (void*) Dummy,
// 202 Reserved
    (void*) Dummy,
// 203 Reserved
    (void*) Dummy,
// 204 Reserved
    (void*) Dummy,
// 205 Reserved
    (void*) Dummy,
// 206 Reserved
    (void*) Dummy,
// 207 Reserved
    (void*) Dummy,
// 208 Reserved
    (void*) Dummy,
// 209 Reserved
    (void*) Dummy,
// 210 Reserved
    (void*) Dummy,
// 211 Reserved
    (void*) Dummy,
// 212 Reserved
    (void*) Dummy,
// 213 Reserved
    (void*) Dummy,
// 214 Reserved
    (void*) Dummy,
// 215 Reserved
    (void*) Dummy,
// 216 Reserved
    (void*) Dummy,
// 217 Reserved
    (void*) Dummy,
// 218 Reserved
    (void*) Dummy,
// 219 Reserved
    (void*) Dummy,
// 220 Reserved
    (void*) Dummy,
// 221 Reserved
    (void*) Dummy,
// 222 Reserved
    (void*) Dummy,
// 223 Reserved
    (void*) Dummy,
// 224 Reserved
    (void*) Dummy,
// 225 Reserved
    (void*) Dummy,
// 226 Reserved
    (void*) Dummy,
// 227 Reserved
    (void*) Dummy,
// 228 Reserved
    (void*) Dummy,
// 229 Reserved
    (void*) Dummy,
// 230 Reserved
    (void*) Dummy,
// 231 Reserved
    (void*) Dummy,
// 232 Reserved
    (void*) Dummy,
// 233 Reserved
    (void*) Dummy,
// 234 Reserved
    (void*) Dummy,
// 235 Reserved
    (void*) Dummy,
// 236 Reserved
    (void*) Dummy,
// 237 Reserved
    (void*) Dummy,
// 238 Reserved
    (void*) Dummy,
// 239 Reserved
    (void*) Dummy,
// 240 Reserved
    (void*) Dummy,
// 241 Reserved
    (void*) Dummy,
// 242 Reserved
    (void*) Dummy,
// 243 Reserved
    (void*) Dummy,
// 244 Reserved
    (void*) Dummy,
// 245 Reserved
    (void*) Dummy,
// 246 Reserved
    (void*) Dummy,
// 247 Reserved
    (void*) Dummy,
// 248 Reserved
    (void*) Dummy,
// 249 Reserved
    (void*) Dummy,
// 250 Reserved
    (void*) Dummy,
// 251 Reserved
    (void*) Dummy,
// 252 Reserved
    (void*) Dummy,
// 253 Reserved
    (void*) Dummy,
// 254 Reserved
    (void*) Dummy,
// 255 Reserved
    (void*) Dummy
};
